#
# This file contains configuration flags to customize your site
#

# SEO Tag Info
name: Anu Ramaswami
url: "https://anuramaswami.com"
description: Professor Anu Ramaswami is the Charles M. Denny, Jr., Chair of Science, Technology, and Public Policy at the Humphrey School of Public Affairs and a professor in the College of Food, Agricultural, and Natural Sciences at the University of Minnesota.
author: Anu Ramaswami
avatar: "/images/anu.png"
logo: "/images/anu.png"
twitter:
  username: AnuRamaswami
social:
  name: Anu Ramaswami
  links:
    - https://twitter.com/anuramaswami
google-site-verification: googlefeae3669bd11c43f.html



# URL of your avatar or profile pic (you could use your GitHub profile pic)


permalink: /:title/

# The release of Jekyll that you're using
version: v3.6.2

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag # Search engine optimization from the official Jekyll seo gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
